{
 "title": "Loki",
 "description": "Loki metrics.",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build, uptime and runtime instance info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{job=\"loki\"}) by (instance)"
    },
    {
     "expr": "max(loki_build_info{job=\"loki\"}) by (instance, branch, goversion, version, revision)"
    }
   ]
  },
  {
   "title": "Number of Loki errors per 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(log_messages_total{level=\"error\"}[5m])",
     "legendFormat": "Number of errors"
    }
   ]
  },
  {
   "title": "Loki's stored chunk entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(loki_ingester_chunk_entries_count[5m])"
    }
   ]
  },
  {
   "title": "Log lines per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "cps", "label": "lines/sec" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_lines_received_total{job=\"loki\"}[5m])",
     "legendFormat": "lines/sec"
    }
   ]
  },
  {
   "title": "Log line data per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_bytes_received_total{job=\"loki\"}[5m]) / 1024",
     "legendFormat": "kb/sec"
    }
   ]
  },
  {
   "title": "Pushes per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (label_replace(label_replace(rate(loki_request_duration_seconds_count{job=\"loki\", route=~\"api_prom_push|loki_api_v1_push\"}[5m]), \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"), \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Queries per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (label_replace(label_replace(rate(loki_request_duration_seconds_count{job=\"loki\", route=~\"api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}[5m]), \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Push latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (loki_request_duration_seconds_bucket{job=~\"loki\", route=~\"api_prom_push|loki_api_v1_push\"}))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (loki_request_duration_seconds_bucket{job=~\"loki\", route=~\"api_prom_push|loki_api_v1_push\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (loki_request_duration_seconds_bucket{job=~\"loki\", route=~\"api_prom_push|loki_api_v1_push\"}))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Query latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (loki_request_duration_seconds_bucket{job=\"loki\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (loki_request_duration_seconds_bucket{job=\"loki\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (loki_request_duration_seconds_bucket{job=\"loki\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Query Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{job=\"loki\", status_code=~\"success|200\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}[5m])) by (route)/sum(rate(loki_request_duration_seconds_count{job=\"loki\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  { "title": "Ingesters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Ingester latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (loki_request_duration_seconds_bucket{job=~\"loki\", route=\"/logproto.Pusher/Push\"}))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (loki_request_duration_seconds_bucket{job=~\"loki\", route=\"/logproto.Pusher/Push\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (loki_request_duration_seconds_bucket{job=~\"loki\", route=\"/logproto.Pusher/Push\"}))",
     "legendFormat": "0.5"
    },
    {}
   ]
  },
  {
   "title": "Ingester Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{job=\"loki\", status_code=~\"success|200\", route=\"/logproto.Pusher/Push\"}[5m])) by (route)/sum(rate(loki_request_duration_seconds_count{job=\"loki\", route=\"/logproto.Pusher/Push\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Distribution of chunk ages when flushed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (loki_ingester_chunk_age_seconds_bucket{job=\"loki\"}))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (loki_ingester_chunk_age_seconds_bucket{job=\"loki\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (loki_ingester_chunk_age_seconds_bucket{job=\"loki\"}))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Distribution of lines per-chunk when flushed.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (loki_ingester_chunk_entries_bucket{job=\"loki\"}))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (loki_ingester_chunk_entries_bucket{job=\"loki\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (loki_ingester_chunk_entries_bucket{job=\"loki\"}))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Distribution of chunk sizes when flushed.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (loki_ingester_chunk_size_bytes_bucket{job=\"loki\"}))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (loki_ingester_chunk_size_bytes_bucket{job=\"loki\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (loki_ingester_chunk_size_bytes_bucket{job=\"loki\"}))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Distribution of chunk utilization when flushed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 54 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (loki_ingester_chunk_utilization_bucket{job=\"loki\"}))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (loki_ingester_chunk_utilization_bucket{job=\"loki\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (loki_ingester_chunk_utilization_bucket{job=\"loki\"}))",
     "legendFormat": "0.5"
    }
   ]
  }
 ]
}